import { Inter } from "next/font/google";
import "./globals.css";
import DrawerAppBar from "@/src/components/DrawerAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DrawerAppBar />
        <div className="container px-4 pt-20 mx-auto">
        {children}
        </div>
        </body>
    </html>
  );
}
